[package]
name = "thumbcloud"
version = "0.0.2"
authors = ["flofriday <flohacksfriday@gmail.com>"]
description = "Thumbcloud is a drop-in software replacement for your USB thumbdrive."
readme = "README.md"
repository = "https://github.com/flofriday/thumbcloud.git"
license = "MIT"

[dependencies]
actix = "^0.5"
actix-web = "^0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
